### ISSUE TITLE
Unified filter condition mapping

### ISSUE THREAD

**Issue by sky-2002** [NeumTry/NeumAI#39]
@ddematheu  @kevinco26 
Currently we are using a dictionary to provide filters on metadata, this approach lacks the following:
- Range based queries 
- "Not equal to" queries
- "Less than" , "greater than" queries 

A simple solution to start with:
- We can expect the user to provide a string of filters, for example - **`"field1 <= value1, field2 != value2"`** instead of a dictionay (`{"field1": "value1", "field2": "value2"}`)
- Then create `FilterCondition` objects by parsing this string:
```python
class FilterCondition:
    
   # We can define FilterOperators
    def __init__(self, column: str, op: FilterOperator, value: Any):
            self.column = column
            self.op = op
            self.value = value
``` 
- Then we can use the filter options of the corresponding databases to map these conditions to.

Let me know your comments on this, I would like to contribute.

**Comment by ddematheu** [comment]
I think this filter condition concept makes sense. We then would need to translate it to the different "languages" that each vectorDB support. Example Pinecone uses something similar to MongoDB's filter language vs Qdrant has a pretty unique style.

**Comment by sky-2002** [comment]
@ddematheu Yes, we can have that mapping to different "languages" of different DBs, that won't be an issue ig. I can take this up, I will first try doing it for a DB and then if it looks good, we can make changes to others, sounds good?

**Comment by ddematheu** [comment]
That sounds good. To maybe simplify the first version, supporting a core set of operators might be enough: "equals", "not equal", "greater than", "less than".

**Comment by sky-2002** [comment]
But ig we also need to define a query language, for now, I am considering SQL, in which we expect the queries, which would be parsed to create these `FilterCondition` objects, which then maps to corressponding queries.

**Comment by ddematheu** [comment]
The filter conditions initially can just be an array of dictionaries that we translate to the class. Something like:

```json
[{
    "field":"abc",
    "operator":"equal",
    "value":"10"
},{...}]
```

```python
from pydantic import BaseModel, Field
class FieldOperator(BaseModel):
    field = Field(...)
    operator = Field(...)
    value = Field(...)
```

**Comment by sky-2002** [comment]
Okay, I had assumed a field value comma separated string, but yes this array of dictionaries would make it easier. In the PR I have used string, if you want it this way, I would change it.

**Comment by ddematheu** [comment]
The array seems better, but open to feedback.

**Comment by sky-2002** [comment]
Okay, how do the filters come from users? I mean in what form?

**Comment by ddematheu** [comment]
def search(self, vector: List[float], number_of_results: int, filter:dict = {})

I think the interface would be the same. the filter object would be a dict. If we want to make it even more explicit, could be updated to:

def search(self, vector: List[float], number_of_results: int, filter:List[dict] = {})

**Comment by sky-2002** [comment]
Made some changes in the PR [here](https://github.com/NeumTry/NeumAI/pull/41).

**Comment by ddematheu** [comment]
Merged PR. Added to 0.0.38 branch.

Migrated your changes to use Pydantic for consistency.

**Comment by ddematheu** [comment]
Implementation across all existing sinks finished. Limited support for operators and nesting conditions. More to come as we get feedback.
