### ISSUE TITLE
LanceDBSink

### ISSUE THREAD

**Issue by abrahimzaman360** [NeumTry/NeumAI#52]
TypeError: LanceDBSink.search() got an unexpected keyword argument 'filters'

**Comment by sky-2002** [comment]
Hey @AbrahimZaman360 , thanks for pointing out, search arguments related issue is already under work, referring issue number 50 and PR #51.

**Comment by ddematheu** [comment]
Pushing fix in today. Will close issue once its fixed.

**Comment by ddematheu** [comment]
0.0.39 published with fix. @AbrahimZaman360

**Comment by abrahimzaman360** [comment]
OSError: LanceError(Index): KMeans: can not train 256 centroids with 1 vectors, choose a smaller K (< 1) instead, /home/runner/work/lance/lance/rust/lance-index/src/vector/kmeans.rs:45:21

**Comment by abrahimzaman360** [comment]
Code: 
`from neumai.DataConnectors import WebsiteConnector
from neumai.Shared import Selector
from neumai.Loaders.HTMLLoader import HTMLLoader
from neumai.Chunkers.RecursiveChunker import RecursiveChunker
from neumai.Sources import SourceConnector
from neumai.EmbedConnectors import OpenAIEmbed
from neumai.SinkConnectors import LanceDBSink
from neumai.Pipelines import Pipeline

# Data Connector:
website_connector = WebsiteConnector(
    url="https://www.doaz.ai/", selector=Selector(to_metadata=["url"])
)

# Source Connector:
source = SourceConnector(
    data_connector=website_connector, loader=HTMLLoader(), chunker=RecursiveChunker()
)

# OpenAI Embed Connector:
openai_embed = OpenAIEmbed(
    api_key="sk-randomrange(2,4)",
)

# Sink Connector:
lancedb = LanceDBSink(uri="data/store", table_name="db-store", create_index=True)


# Pipeline:
pipeline = Pipeline(sources=[source], embed=openai_embed, sink=lancedb)

# Vector count:
print(f"Vectors stored: {pipeline.run()}")

# Search:
results = pipeline.search(query="What is DoAZ all about?", number_of_results=3)

for result in results:
    print(result.metadata)
`

**Comment by abrahimzaman360** [comment]
Running example!

**Comment by abrahimzaman360** [comment]
I've upgraded the package aswell!

**Comment by ddematheu** [comment]
Thanks for providing this details. Re-opening issue to fix this.

**Comment by ddematheu** [comment]
Issue seems to be related to the creation of the index which has a default size of 256. (LanceDB doesn't create the index by default).

@sky-2002 thoughts on removing the create index code or only calling it if the table is bigger than 256?

**Comment by ddematheu** [comment]
Pinged LanceDB folks for feedback on best practices.

**Comment by sky-2002** [comment]
> @sky-2002 thoughts on removing the create index code or only calling it if the table is bigger than 256?

@ddematheu Yeah we can do that. But its useful to check this doc once - https://lancedb.github.io/lancedb/ann_indexes/. I will just summarize from it what is relevant to us, but do take a look if you want details:
- For many use-cases, datasets under 100K vectors won't require index creation at all. If you can live with < 100ms latency, skipping index creation is a simpler workflow while guaranteeing 100% recall.
- We can use the `num_partitions` argument to alter that 256 centroids thing, it is customizable. So if your data size is say 100 vectors, we can set `num_partitions` to something less than that.

**Comment by ddematheu** [comment]
Reading through it. One option we could do is have an argument as part of
the sink configuration to create index and it can be enabled by folks
moving in 100k+ vectors.

The only issue there is that we would just need to ensure that by the time
the user 'search' there are already enough vectors.

Similar thing with the centroids. Could be a configuratiin parameter. Could
maybe automate aome of this by coming up with some formula that returns the
number of partitions given an approximate vector count.

To unblock this quickly, I am thinking on moving forward with having these
exposed as simple config options and figuring out how to optimize for ease
of use later. Thoughts?

**Comment by sky-2002** [comment]
@ddematheu Yes, sounds good to expose as config options as a quick solution. 

**Update**: Created a PR for this.

**Comment by ddematheu** [comment]
Taking a look at PR (sorry for delay).

**Comment by ddematheu** [comment]
PR merged. Will be released tomorrow as part of 0.0.40

**Comment by abrahimzaman360** [comment]
hey please create an example for Lancedb usage because I'm still facing issues! thanks

**Comment by sky-2002** [comment]
Sure @AbrahimZaman360 , I will take a look, need to get this sorted. Till then, can you share what dimension vectors you have in the table and how many vectors?

**Comment by abrahimzaman360** [comment]
> Sure @AbrahimZaman360 , I will take a look, need to get this sorted. Till then, can you share what dimension vectors you have in the table and how many vectors?

I don't know, currently I'm just testing neum AI.

**Comment by sky-2002** [comment]
@AbrahimZaman360 Okay, so for me, everything's working. I think there is issue with the number of vectors, the `num_partitions` and `num_sub_vectors` that you are using. I can help more if I can get some information regarding data size and dimension. Otherwise its difficult to debug. Can you share the code snippet you are using - right from creating the `LanceDBSink` to using the `search` method please?

**Comment by abrahimzaman360** [comment]
> @AbrahimZaman360 Okay, so for me, everything's working. I think there is issue with the number of vectors, the `num_partitions` and `num_sub_vectors` that you are using. I can help more if I can get some information regarding data size and dimension. Otherwise its difficult to debug. Can you share the code snippet you are using - right from creating the `LanceDBSink` to using the `search` method please?

Based on an example on the main project readme, it is saying that create a table first then add the vectors.
But anyway.

Please share an example with Lancdb it will be  enough I think ✨

**Comment by ddematheu** [comment]
Added official docs for LanceDB: https://docs.neum.ai/components/sink-connectors/LanceDBSink

**Comment by ddematheu** [comment]
Will wait for confirmation of it working before closing

**Comment by ddematheu** [comment]
Closing as issue was fixed and didn't get additional feedback.
